version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && ./bin/dev"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/rails-docker
